title: Portafolio de Luis Alfonso López
description: QA Engineer Junior con formación en Psicología y Recursos Humanos.
theme: jekyll-theme-minimal

# Opcional: íconos de redes sociales (usa solo los que quieras)
social_links:
  github: https://github.com/wichistj
  linkedin: https://linkedin.com/in/tuusuario
