title: Luis Alfonso López
description: QA Engineer Junior | linkedin.com/in/luis-alfonso-lopez-gonzalez-71758453
theme: jekyll-theme-minimal
logo: /assets/img/_Y0A9481lo (1).jpeg
show_downloads: false

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-feed
